### PR TITLE
Support for paypal error 10486

### LINKED ISSUE #143: Error Code 10486 in Paypal Express
Full error background: https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/

When returning from a redirect to paypal and submitting the `completePayment` gateway request, paypal can return error code 10486. The associated error message is "This transaction couldn't be completed. Please redirect your customer to PayPal."

Should omnipay be handling this?

I mean, should the `completePayment` error response object have a `isRedirect` set to true?

At the moment, my app would need to manually check for this error code and somehow build the same redirect url again to send the customer back to paypal, but that seems like it should be a job for the gateway driver perhaps?

Let me know if I am way off, or correct. I will then look at implementing a redirect response into the `completePayment` response object within this driver.

### PR DESCRIPTION
**Pull request by lukeholder**
Error 10486 allows for a redirect back to paypal during a completePayment call.

This pull requests adds a modified CompletePaymentRequest which returns a CompletePaymentResponse which could be successful as usual OR a redirect response if error 10486 is detected.

Documentation: https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/

Would love some feedback on this. This attempts to fix #143

### CODE REVIEW

**Comment by lindseydiloreto** [comment]
Yes!! This would be hugely helpful for us. :+1:

**Comment by leith** [comment]
@lukeholder So the flow after `completePurchase` would change to include an `isRedirect()` block as well? i.e. currently:
```php
$request = $gateway->completePurchase($purchaseFields);
$reponse = $request->send();

if ($response->isPending()) {
  // pending behaviour
}
else if ($response->isSuccessful()) {
  // success behaviour
}
else {
 // error probably using $response->getMessage()
}
```
...would change to be:
```php
$request = $gateway->completePurchase($purchaseFields);
$reponse = $request->send();

if ($response->isPending()) {
  // pending behaviour
}
else if ($response->isSuccessful()) {
  // success behaviour
}
else if ($response->isRedirect()) {
  // redirect back to $response->getRedirectUrl() - docs seem to indicate should be the same URL
}
else {
 // error probably using $response->getMessage()
}
```

Am I getting this right?

**Comment by lukeholder** [comment]
Your example is pretty much it - although I personally have never used the isPending.

Happy to add tests, but kinda hard when there are not any exisitng tests for completePayment itself?

I see the mock request data for completePaymentSuccess and completePaymentFailure but they are not even used in the tests, so I went ahead and added mock request data for what I called completePaymentFailureRedirect.

Let me know if I missed something, happy to be shown where the completePayment tests are. Thanks.

**Comment by lukeholder** [comment]
@leith tests added. Let me know if there is anything else I can do to get this merged.

**Comment by leith** [comment]
@lukeholder The `isPending()` was something I added to omnipay-common as a part of getting PayPal sorted - I'd seen it with other gateways as well, where sometimes you ended up in a "we haven't made up our mind yet, we'll keep you posted" type response. PayPal does this when there's a hold on the funds for some reason, e.g. it was detected as suspicious, or you're in sandbox mode with a hold on the funds.

Looks like I'll just need to add the `isRedirect()` check on the responses then (for all gateways I integrate with). The unit test looks fine and the Travis build says it's got 100% coverage on the new methods, so that's good.

Is there some way to simulate this response from within the PayPal sandbox rather than faking it with a unit test Mock response?

**Comment by delatbabel** [comment]
OK I just pushed a release and so I will merge this now. Please confirm that it all works in production and then I will tag.

**Comment by lukeholder** [comment]
@leith Yes, you can simulate the error code by following these steps:

1. Login to https://www.sandbox.paypal.com using your *buyer's test PayPal account*.

2. Replace the contents of the street address Line-1 of the buyer's test credit card, with CCREJECT-REFUSED.

3. Execute a typical Express Checkout payment flow against the Sandbox test environment using the same buyer account and with the same credit card that you just modified.

4. When you execute DoExpressCheckoutPayment, error code 10486 will be returned. Your code should redirect the buyer back to PayPal using the same redirect URL used to start the checkout flow and the same Express Checkout token.

The above steps were taken from the document on error code 10486 here: https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/

**Comment by lukeholder** [comment]
@leith Thanks for merging. Can you leave a comment here when you tag the release. Thanks.

@lindseydiloreto can you use the beta build I sent to you (of Craft Commerce) and see if the error is fixed in both test mode then production.

**Comment by delatbabel** [comment]
Please confirm that it all works in production and then I will tag.

**Comment by judgej** [comment]
Is there any documentation on the use of `isPending()`? How, for example, should it be checked in conjunction with `isSuccessful()`? For most gateways, a pending result can be treated as successful, but with a small risk of it being later withdrawn, so I'm guessing `isSuccessful()` needs to be true before even looking at `isPending()`.

Or perhaps not?

Just a side note: the docblock for `isPending()` still contains the comment from `isSuccessful()`. It is also not in the interface, so there is a little inconsistency there - maybe adding it to the interface would be a BC break for gateways that don't use `AbstractResponse`, but do we have any drivers written like that?

**Comment by lukeholder** [comment]
@delatbabel this is confirmed working in production by a couple of our users who were previously seeing error 10486. Could we go ahead and tag a release?

**Comment by delatbabel** [comment]
2.6.1 tagged

**Comment by lukeholder** [comment]
Thanks

**Pull request merged**
