### PR TITLE
Implementing Express gateway order request

### PR DESCRIPTION
**Pull request by nicksnellockts**
These changes implement the Express gateway order request and add the 'Number' attribute to items in the order.

### CODE REVIEW

**Comment by delatbabel** [comment]
You have PR'ed this and withdrawn the PR a few times so I'll wait until you can confirm that this is OK to merge before I pull it in.

**Comment by nicksnellockts** [comment]
I had problems finding why it was failing tests. All sorted now.

**Comment by nicksnellockts** [comment]
Just to be clear, this is OK to merge now

**Comment by delatbabel** [comment]
Merged. I don't have production keys for paypal express so I will leave it to you to confirm that it works in production and then I will tag it for release.

**Comment by lukeholder** [comment]
@nicksnellockts Isn't this considered a breaking change? You are now expecting all `ItemBag` to implementations to have a `getCode` etc. Seeing as the number is optional in payal:

logo

 Could you make this work with a regular `ItemBag` too?

**Comment by nicksnellockts** [comment]
It should be optional, it was certainly intended to be.

**Comment by delatbabel** [comment]
OK I will leave this untagged until the ItemBag implementation is fixed.

**Comment by nicksnellockts** [comment]
@lukeholder can you give me an example of what this change breaks please?

**Comment by tunderdomb** [comment]
@nicksnellockts let me give you an example:

- [AbstractRequest:308](https://github.com/thephpleague/omnipay-paypal/blob/master/src/Message/AbstractRequest.php#L308) makes the assumption that an item has a `getCode`method.
- The `ItemBag` only required to contain `ItemInterface` instances.
- The `AbstractRequest`'s assumption is wrong, because an item is *not* guaranteed to have a `getCode` method.
- If someone tries to pay with PayPal and the `ItemBag` only contains plain `ItemInterfaces`, `getCode` will throw: https://github.com/thephpleague/omnipay/issues/379, https://github.com/thephpleague/omnipay-paypal/issues/135

**Comment by nicksnellockts** [comment]
@tunderdomb This can only happen if the ItemBag is created outside of the OmniPay system. If the ItemBag is created using the normal method, it will be a bag of PayPal items. However, its a simple change to cater for this so I will do so.

**Comment by tunderdomb** [comment]
@nicksnellockts Indeed, because people might take advantage of the generic nature of the ItemBag, so they can extend ItemInterface, and populate a bag with objects that both satisfy the interface and their own needs. However, with the provided methods a custom extended item class is impossible.

I went ahead and made a PR: https://github.com/thephpleague/omnipay-paypal/pull/141 if you'd look at it and see if it's something we both had in mind. 
Thank you.

**Comment by nicksnellockts** [comment]
Yes, that's exactly what I was going to do. Thanks for saving me the trouble :-)

**Comment by pdbreen** [comment]
Glad you guys are already on top of this!  I just hit the getCode error after an overdue composer update for one of my projects.  Down versioned to v2.5.3 until PR #141 gets versioned.

**Comment by delatbabel** [comment]
I have merged #141, waiting on confirmation from someone that it works in production before I tag.

**Pull request merged**
