### PR TITLE
Returned proper payment error details

### PR DESCRIPTION
**Pull request by sameerkanda**

### CODE REVIEW

**Comment by kayladnls** [comment]
I can't merge until the build passes.

**Comment by sameerkanda** [comment]
Hmm, not sure what to do:

Problem: Paypal REST sometimes returns an object (array) of error message details, but I believe ->getMessage() is expected to output a string all the time?

Possible solution: Maybe we can add two more methods to ResponseInterface/AbstractResponse: messageHasDetails and getMessageDetails (not sure if getMessageDetails should return an array as the message, or convert it to a string somehow)? I'm sort of new to omnipay, so not sure what the best solution to this is. I can of course manually get message details via ->getData()['details'], but that sort of defeats the purpose of using omnipay. Any recommendations?

**Comment by delatbabel** [comment]
There are a small number of other gateways (PaymentWall is one that springs to mind) that have a method to return an array of error details (e.g. one error per field passed) instead of or as well as a single error message. In that case what I tend to code is to have getMessage() return a string comprised of the error string as well as a parseable list of error field details.

For example, you could implement something like the following code:

         $message = '';
         if (isset($this->data['message'])) {
             $message = $this->data['message'];
         }
         if (isset($this->data['details']) && is_array($data['details'])) {
            foreach ($data['details'] as $key => $value) {
                $message .= "; $key: $value";
            }
         }
         return $message;

**Comment by sameerkanda** [comment]
Yes this implementation would work to pull in all errors, which would be very useful for admin purposes, but OmniPay is still missing other methods like getDisplayMessage (or something similar), where we can simply take the message and pass it to the front-end. PayPal Rest is also missing a way to save/get the token from some sort of cache (because otherwise it’s making an additional request to get the token all the time).

For now I’ve decided to create a PayPalRest class of my own that extends PayPal\RestGateway, and add these features in. This was the quickest solution for me to implement and meet my clients needs. Thanks for your help anyways, overall omnipay has helped me save a ton of time!

**Comment by judgej** [comment]
Some gateways provide messages you *can* send to the front end and put in front of a user. Some do not, and must only be logged for an administrator. Some provide codes that can be used to target a translated error message. Some have no codes, or codes that do not provide that level of targeted detail. It is difficult to find the happy medium that can be supported across the drivers.

What may be good, is a separate project to handle omnipay message translations - a common set of messages, with substitution placeholders, and mappings from the codes and messages of all the gateways (which could ultimately be put into the gateways as metadata).

**Comment by sameerkanda** [comment]
Yup, that totally makes sense. I would have done this myself and submitted a pull request, but then realized it was going to take way to long going through all the possible error message for all the gateways. lol. My client has a need to start off with PayPal, and extend to other gateways as needed, so we’re just going to take things one at a time. Thanks for your help once again though!

**Comment by delatbabel** [comment]
> For now I’ve decided to create a PayPalRest class of my own that extends PayPal\RestGateway, and add these features in.

That's what open source code is for!

**Pull request closed without merging**
