### PR TITLE
Added Void

### PR DESCRIPTION
**Pull request by alexw23**
Realised Void was missing. I haven't added a test yet - but looking for a code review to get this merged in quite quickly.

### CODE REVIEW

**Comment by alexw23** [comment]
@kayladnls any concerns?

**Comment by kayladnls** [comment]
Looks solid, in happily to merge. Can you squash it, though?

**Comment by cmtatro85** [comment]
Any Update on this? Anything I can do to help?

Not sure why this was closed before the pull request was completed.

**Comment by kayladnls** [comment]
I'm not sure either. I was going to reopen for merge, but the repository has been deleted. @alexw23 thoughts?

**Comment by alexw23** [comment]
@delatbabel was working on this see: #58

**Pull request closed without merging**
