### PR TITLE
Implemented RestRefundCaptureRequest to refund captured payments. And RestVoidRequest to void a previously authorized payments

### PR DESCRIPTION
**Pull request by fraterblack**

### CODE REVIEW

**Comment by delatbabel** [comment]
Can we get some test coverage on the new methods please?

**Comment by fraterblack** [comment]
I have added tests to new methods.

**Comment by delatbabel** [comment]
Thanks for the PR. Please confirm that this works in production for you and then I will tag for release.

**Comment by fraterblack** [comment]
I have used these new methods in a project for a long time. Is it enough?

**Comment by delatbabel** [comment]
2.6.1 tagged

**Pull request merged**
