### PR TITLE
use the POST HTTP request

### PR DESCRIPTION
**Pull request by karneds**
Fix issue #112

### CODE REVIEW

**Comment by delatbabel** [comment]
Why is this change required?

**Comment by karneds** [comment]
Starting on September 30, 2016, PayPal will only allow the use of the POST request method for classic NVP/SOAP APIs

https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1927&viewlocale=en_US

**Comment by delatbabel** [comment]
Noted, thanks for the update.  I will merge this. Once I have done so can you please pull from the dev-master branch and confirm that it works in production? I don't have keys for the classic APIs, i only use the REST API myself.

**Comment by karneds** [comment]
> Once I have done so can you please pull from the dev-master branch and confirm that it works in production?
I just checked. It`s working.

**Pull request merged**
