### PR TITLE
Implement list Plan and tests

### PR DESCRIPTION
**Pull request by islamdarwish**
Implementing listing billing plans and its tests as well.

### CODE REVIEW

**Comment by delatbabel** [comment]
PHP 5.3 support can be removed in fact but at least you got it working.  I will merge this now, thanks for the contribution. Can you confirm that this works for you in production and if that is the case I will tag for release.

**Comment by islamdarwish** [comment]
You are welcome, go ahead man!! i checked it in production and it is working just fine.

**Comment by islamdarwish** [comment]
Can you please tag it for release as soon as possible to be able to get it when `composer update` @delatbabel

**Comment by delatbabel** [comment]
Released as v2.6.4

**Pull request merged**
