### PR TITLE
PayPal REST API: Adding support for the 'paypal' payment_method

### PR DESCRIPTION
**Pull request by pohnean**
This PR adds support for the 'paypal' payment_method for the REST API. Implementation of this is adapted from the Paypal_Express Checkout payment method, utilising the same 'completePurchase' method to execute the payment after authorization is given.

### CODE REVIEW

**Comment by pohnean** [comment]
This PR also fixes issue #34 (you can now pass PayerID to completePurchase, REST api does not need the token to be passed in)

**Comment by delatbabel** [comment]
I think that this duplicates the work that I have already done in PR #42

**Comment by pohnean** [comment]
Well, mine uses implements completePurchase function for handling redirects, making it compatible with the PayPal_Express version. Users currently on the PayPal_Express method can easily switch to PayPal_Rest using my version.

**Comment by Jellyfrog** [comment]
Could someone take a look at this? Or the other PR that does the same thing? @kayladnls maybe

**Comment by kayladnls** [comment]
@pohnean this looks really good. Thank you for the PR. 

It does a lot of the same things that #42 does, however, I prefer the completePurchase function, over Execute, as it falls in line with the rest of the Omnipay gateways, and the API that most people are familiar with.

**Pull request merged**
