### PR TITLE
Adding Void to Paypal Express

### PR DESCRIPTION
**Pull request by alexw23**

### CODE REVIEW

**Comment by kayladnls** [comment]
Thanks for this, @alexw23. Can we get some tests to cover the new functionality? And also fix the formatting so Codesniffer stops failing the build?

**Comment by delatbabel** [comment]
I could use this functionality in REST and I may as well include it for Express.  Are there any objections to me pulling this branch and re-submitting the PR with fixes and tests?

**Comment by alexw23** [comment]
@delatbabel I haven't started the tests so more than happy for you to make the changes.

**Comment by kayladnls** [comment]
@delatbabel no objections from me. Since @alexw23 is okay with it too, I'll go ahead and close this.

**Comment by alexw23** [comment]
@delatbabel Can you reference this once you have submitted the PR?

**Comment by delatbabel** [comment]
OK it might be another week or so before I can get onto this, it's hectic at work at the moment.

**Comment by delatbabel** [comment]
All done, sorry about the delay.

**Pull request closed without merging**
