### PR TITLE
[WIP] 3.0 Upgrade

### PR DESCRIPTION
**Pull request by barryvdh**
This is a test to define an upgrade path and check for problems. The Card + customer split is a bit confusing, because it's difficult to tell where it belongs (customer object in the root of the request options, or as part of shipping/billing in the card?). Together with forcing a currency, these seem to be the biggest end-user changes also.

There are some things to be aware of, like immutability, but the rest should be relative straight forward.

Todo:
- [ ] Make the new `isCompleted()` correct for all cases.
- [ ] Return the correct status codes
- [ ] Return amounts as objects from responses

Notes:

Namespace upgrade:
```php
use Omnipay\Tests\*;
—> 
use League\Omnipay\Tests\*;

use Omnipay\Common\*;
—>
use League\Omnipay\Common\*;
```

Split card + customer objects
Add isCompleted method

Use new HttpClient
 - `array()` instead of `null` for headers argument when empty
 - `getBody()->getContents()` for string value
 - `json_decode($body, true);` instead of `$response->json()`
 - also Encode json send data manually
 - Remove event dispatchers
 ```php
$this->httpRequest->query->get('PayerID')
—>$this->query(‘PayerId’)
```

Use the PSR-7 factories
```php
$httpRequest = $this->httpClient->createRequest(..) 
—> $httpRequest = Factory::createRequest(..)
```

Remove < php5.6 code (search for phpversion())

Use new Amount object for formatting
```php
 - $this->formatCurrency($item->getPrice())
—>
$amount = new Amount($item->getPrice(), $this->getCurrency());
// or
$amount = Amount::fromDecimal($item->getPrice(), $this->getCurrency());

$amount->getFormatted();
```

PSR-7 requests/responses are immutable, so pass new instance to gateway if needed

```php
$this->getHttpRequest()->query->replace(array(     
'token' => 'GET_TOKEN',     
'PayerID' => 'GET_PAYERID', 
)); 
—>
$httpRequest = $this->getHttpRequest();

 $query = $httpRequest->getQueryParams(); 
$query['token'] = 'GET_TOKEN'; $query['PayerID'] = 'GET_PAYERID';  

$httpRequest = $httpRequest->withQueryParams($query);  

$this->gateway = new ExpressGateway($this->getHttpClient(), $httpRequest);
```

### CODE REVIEW

**Comment by delatbabel** [comment]
@barryvdh this is probably not the gateway I would have chosen to make these changes on.  PayPal has 3 different gateways, the Express, Pro and REST gateways.  The REST gateway is the one that PayPal are recommending new accounts are set up with although Express is still the most commonly used.

I would have started with just a simple REST-only gateway such as Stripe or PIN or Fat Zebra.

In any case I think what your changes will do is make it work for the Express gateway while breaking the other two.  So I can't see how this can be merged even as a test version yet.  I don't have an Express account for testing, only a REST account.

**Comment by barryvdh** [comment]
I chose this because it was the most popular and complex to find problems with omnipay common v3 and define an upgrade path. 

But why would this break for other 2? All tests are still green.

**Comment by delatbabel** [comment]
Unless you're updating the code for all 3 gateways, wouldn't each of the other 2 gateways that you're not updating be incompatible with Omnipay v3?

**Comment by barryvdh** [comment]
I updated the abstract code for request /responses, and replaced all namespaces and amounts in the project and all tests are green, so are not all gateways covered? What error do you get?

**Comment by garak** [comment]
I'm trying the new branch, but it looks like there's still the `Omnipay` namespace in common, not `League\Omnipay`. See for example https://github.com/thephpleague/omnipay-common/blob/master/src/Common/AbstractGateway.php

**Comment by patrickarnold79** [comment]
I am having the same problem as @garak. Anything I can do here? Happy to contribute :)

**Pull request closed without merging**
